version: 2
updates:

# GitHub Actions workflow updates for "master" branch
  - package-ecosystem: "github-actions"
    target-branch: master
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    assignees:
      - CI/CD Maintainers
    reviewers:
      - Maintainers
    labels:
      - "pr: CI"